<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neighbours [
<!ELEMENT neighbours (province+)>
<!ELEMENT province (name, neighbour+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT neighbour (#PCDATA)>
]>
<neighbours>
	<province>
		<name>alaska</name>
		<neighbour>kamchatka</neighbour>
		<neighbour>northwest territory</neighbour>
		<neighbour>alberta</neighbour>
	</province>
	<province>
		<name>northwest territory</name>
		<neighbour>alaska</neighbour>
		<neighbour>alberta</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>greenland</neighbour>
	</province>
	<province>
		<name>greenland</name>
		<neighbour>northwest territory</neighbour>
		<neighbour>quebec</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>iceland</neighbour>
	</province>
	<province>
		<name>alberta</name>
		<neighbour>northwest territory</neighbour>
		<neighbour>western united states</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>alaska</neighbour>
	</province>
	<province>
		<name>ontario</name>
		<neighbour>northwest territory</neighbour>
		<neighbour>eastern united states</neighbour>
		<neighbour>western united states</neighbour>
		<neighbour>quebec</neighbour>
		<neighbour>alberta</neighbour>
		<neighbour>greenland</neighbour>
	</province>
	<province>
		<name>quebec</name>
		<neighbour>eastern united states</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>greenland</neighbour>
	</province>
	<province>
		<name>western united states</name>
		<neighbour>eastern united states</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>alberta</neighbour>
		<neighbour>central america</neighbour>
	</province>
	<province>
		<name>eastern united states</name>
		<neighbour>western united states</neighbour>
		<neighbour>ontario</neighbour>
		<neighbour>quebec</neighbour>
		<neighbour>central america</neighbour>
	</province>
	<province>
		<name>central america</name>
		<neighbour>eastern united states</neighbour>
		<neighbour>western united states</neighbour>
		<neighbour>venezuela</neighbour>
	</province>
	<province>
		<name>venezuela</name>
		<neighbour>peru</neighbour>
		<neighbour>brazil</neighbour>
		<neighbour>central america</neighbour>
	</province>
	<province>
		<name>brazil</name>
		<neighbour>venezuela</neighbour>
		<neighbour>peru</neighbour>
		<neighbour>argentina</neighbour>
		<neighbour>north africa</neighbour>
	</province>
	<province>
		<name>peru</name>
		<neighbour>venezuela</neighbour>
		<neighbour>brazil</neighbour>
		<neighbour>argentina</neighbour>
	</province>
	<province>
		<name>argentina</name>
		<neighbour>peru</neighbour>
		<neighbour>brazil</neighbour>
	</province>
	<province>
		<name>iceland</name>
		<neighbour>greenland</neighbour>
		<neighbour>scandinavia</neighbour>
		<neighbour>great britain</neighbour>
	</province>
	<province>
		<name>scandinavia</name>
		<neighbour>iceland</neighbour>
		<neighbour>ukraine</neighbour>
		<neighbour>great britain</neighbour>
		<neighbour>northern europe</neighbour>
	</province>
	<province>
		<name>great britain</name>
		<neighbour>scandinavia</neighbour>
		<neighbour>northern europe</neighbour>
		<neighbour>western europe</neighbour>
		<neighbour>iceland</neighbour>
	</province>
	<province>
		<name>ukraine</name>
		<neighbour>scandinavia</neighbour>
		<neighbour>northern europe</neighbour>
		<neighbour>southern europe</neighbour>
		<neighbour>middle east</neighbour>
		<neighbour>afghanistan</neighbour>
		<neighbour>ural</neighbour>
	</province>
	<province>
		<name>northern europe</name>
		<neighbour>scandinavia</neighbour>
		<neighbour>great britain</neighbour>
		<neighbour>western europe</neighbour>
		<neighbour>ukraine</neighbour>
		<neighbour>southern europe</neighbour>
	</province>
	<province>
		<name>western europe</name>
		<neighbour>great britain</neighbour>
		<neighbour>northern europe</neighbour>
		<neighbour>southern europe</neighbour>
		<neighbour>north africa</neighbour>
	</province>
	<province>
		<name>southern europe</name>
		<neighbour>middle east</neighbour>
		<neighbour>northern europe</neighbour>
		<neighbour>western europe</neighbour>
		<neighbour>north africa</neighbour>
		<neighbour>ukraine</neighbour>
		<neighbour>egypt</neighbour>
	</province>
	<province>
		<name>north africa</name>
		<neighbour>brazil</neighbour>
		<neighbour>western europe</neighbour>
		<neighbour>southern europe</neighbour>
		<neighbour>egypt</neighbour>
		<neighbour>congo</neighbour>
		<neighbour>east africa</neighbour>
	</province>
	<province>
		<name>egypt</name>
		<neighbour>middle east</neighbour>
		<neighbour>north africa</neighbour>
		<neighbour>southern europe</neighbour>
		<neighbour>east africa</neighbour>
	</province>
	<province>
		<name>east africa</name>
		<neighbour>middle east</neighbour>
		<neighbour>north africa</neighbour>
		<neighbour>south africa</neighbour>
		<neighbour>egypt</neighbour>
		<neighbour>congo</neighbour>
		<neighbour>madagascar</neighbour>
	</province>
	<province>
		<name>congo</name>
		<neighbour>north africa</neighbour>
		<neighbour>south africa</neighbour>
		<neighbour>east africa</neighbour>
	</province>
	<province>
		<name>madagascar</name>
		<neighbour>south africa</neighbour>
		<neighbour>east africa</neighbour>
	</province>
	<province>
		<name>south africa</name>
		<neighbour>congo</neighbour>
		<neighbour>east africa</neighbour>
		<neighbour>madagascar</neighbour>
	</province>
	<province>
		<name>ural</name>
		<neighbour>ukraine</neighbour>
		<neighbour>siberia</neighbour>
		<neighbour>china</neighbour>
		<neighbour>afghanistan</neighbour>
	</province>
	<province>
		<name>siberia</name>
		<neighbour>ural</neighbour>
		<neighbour>china</neighbour>
		<neighbour>mongolia</neighbour>
		<neighbour>irkutsk</neighbour>
		<neighbour>yakutsk</neighbour>
	</province>
	<province>
		<name>yakutsk</name>
		<neighbour>siberia</neighbour>
		<neighbour>irkutsk</neighbour>
		<neighbour>kamchatka</neighbour>
	</province>
	<province>
		<name>kamchatka</name>
		<neighbour>yakutsk</neighbour>
		<neighbour>irkutsk</neighbour>
		<neighbour>mongolia</neighbour>
		<neighbour>japan</neighbour>
		<neighbour>alaska</neighbour>
	</province>
	<province>
		<name>irkutsk</name>
		<neighbour>yakutsk</neighbour>
		<neighbour>kamchatka</neighbour>
		<neighbour>mongolia</neighbour>
		<neighbour>siberia</neighbour>
	</province>
	<province>
		<name>japan</name>
		<neighbour>kamchatka</neighbour>
		<neighbour>mongolia</neighbour>
	</province>
	<province>
		<name>mongolia</name>
		<neighbour>kamchatka</neighbour>
		<neighbour>japan</neighbour>
		<neighbour>china</neighbour>
		<neighbour>siberia</neighbour>
		<neighbour>irkutsk</neighbour>
	</province>
	<province>
		<name>china</name>
		<neighbour>mongolia</neighbour>
		<neighbour>siam</neighbour>
		<neighbour>india</neighbour>
		<neighbour>afghanistan</neighbour>
		<neighbour>ural</neighbour>
		<neighbour>siberia</neighbour>
	</province>
	<province>
		<name>afghanistan</name>
		<neighbour>ural</neighbour>
		<neighbour>china</neighbour>
		<neighbour>india</neighbour>
		<neighbour>middle east</neighbour>
		<neighbour>ukraine</neighbour>
	</province>
	<province>
		<name>middle east</name>
		<neighbour>afghanistan</neighbour>
		<neighbour>india</neighbour>
		<neighbour>east africa</neighbour>
		<neighbour>egypt</neighbour>
		<neighbour>southern europe</neighbour>
		<neighbour>ukraine</neighbour>
	</province>
	<province>
		<name>india</name>
		<neighbour>china</neighbour>
		<neighbour>siam</neighbour>
		<neighbour>middle east</neighbour>
		<neighbour>afghanistan</neighbour>
	</province>
	<province>
		<name>siam</name>
		<neighbour>india</neighbour>
		<neighbour>china</neighbour>
		<neighbour>indonesia</neighbour>
	</province>
	<province>
		<name>indonesia</name>
		<neighbour>new guinea</neighbour>
		<neighbour>western australia</neighbour>
		<neighbour>siam</neighbour>
	</province>
	<province>
		<name>new guinea</name>
		<neighbour>indonesia</neighbour>
		<neighbour>eastern australia</neighbour>
	</province>
	<province>
		<name>western australia</name>
		<neighbour>indonesia</neighbour>
		<neighbour>new guinea</neighbour>
		<neighbour>eastern australia</neighbour>
	</province>
	<province>
		<name>eastern australia</name>
		<neighbour>new guinea</neighbour>
		<neighbour>western australia</neighbour>
	</province>
</neighbours>
