<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en [
<!ELEMENT en (pair+)>
<!ELEMENT pair (key, value)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<en>
	<pair>
		<key>PLAY_OFFLINE</key>
		<value>play offline</value>
	</pair>
	<pair>
		<key>PLAY_ONLINE</key>
		<value>play online</value>
	</pair>
	<pair>
		<key>SETTINGS</key>
		<value>settings</value>
	</pair>
	<pair>
		<key>RULES</key>
		<value>rules</value>
	</pair>
	<pair>
		<key>EXIT</key>
		<value>exit</value>
	</pair>
</en>